language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
    - libsdl2-dev 
    - libegl1-mesa-dev
    - libgles2-mesa-dev
    - libsdl2-gfx-dev

notifications:
  email:
    on_success: never