name: Continuous Integration

on: 
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1

      - name: Install required dependencies for building
        run: sudo apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev libsdl2-gfx-dev

      - name: Build release with Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Test with Cargo
        uses: actions-rs/cargo@v1
        with:
          command: test